on: 
  repository_dispatch:
    types: [incident_report]
jobs:
  handel-incident:
   runs-on: ubuntu-latest
   steps:
     - name: print incident details
       run: echo "incident reported"
  

    
# on: 
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: "Choose ENV"
#         required: true
#         default: "staging"
#         type: choice
#         options:
#           - staging
#           - production
          

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy app
#         run: echo "Deploying the app to ${{inputs.environment}}"
    
