on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose ENV"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
          

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        run: echo "Deploying the app to ${{inputs.environment}}"
    
